import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Zap } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — QuizLab" },
      {
        name: "description",
        content:
          "Read the terms and conditions for using QuizLab, the AI-powered PDF-to-quiz study game.",
      },
      { property: "og:title", content: "Terms & Conditions — QuizLab" },
      {
        property: "og:description",
        content:
          "The rules for using QuizLab: what you can upload, what we generate, and how we handle your content.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="mx-auto min-h-screen w-full max-w-3xl px-5 py-10">
      <header className="mb-10 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2">
          <span className="grid size-10 place-items-center rounded-2xl bg-primary text-primary-foreground">
            <Zap className="size-5" />
          </span>
          <span className="font-display text-xl font-bold">QuizLab</span>
        </Link>
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="size-4" />
          Back to app
        </Link>
      </header>

      <article className="surface-card space-y-8 p-6 sm:p-8">
        <div className="space-y-2">
          <h1 className="font-display text-3xl font-bold">Terms & Conditions</h1>
          <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">1. Use of QuizLab</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            QuizLab turns PDF documents into interactive quizzes using AI. You may use the service for personal studying, teaching, and other lawful purposes. Commercial resale of generated quizzes is not allowed without permission.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">2. What you upload</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            You retain ownership of any PDFs you upload. By uploading, you give us permission to process the text so we can generate quizzes and fact-checks. Do not upload content you do not have the right to use, or content that is illegal, harmful, hateful, or explicit.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">3. AI-generated content</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Quizzes, answers, explanations and fact-checks are generated by AI and may contain errors. Always verify important facts against your course materials or trusted sources. We do not guarantee that every question is correct.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">4. Account & data</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Currently, quiz sessions are stored locally in your browser during a session. We do not permanently store your PDFs or quiz results unless you explicitly save them through a future account feature.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">5. Fair use</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Do not abuse the service through automation, scraping, or attempts to bypass limits. We may suspend access for behavior that harms the platform or other users.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">6. Changes to these terms</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            We may update these terms as the app evolves. Continued use of QuizLab after changes means you accept the updated terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold">7. Contact</h2>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Questions? Reach out through the app or email our support team.
          </p>
        </section>
      </article>
    </main>
  );
}
